package com.boye.bitcoin;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.assertNotNull;

public class MultisigExampleTest {
    @Test public void testAppHasAGreeting() {

    }
}
